server:
  port: 9111
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix= 1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@keyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix= 1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@keyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix= 1

        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix= 1

        - id: car
          uri: lb://car
          predicates:
            - Path=/car/**
          filters:
            - StripPrefix= 1

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1
